### ISSUE TITLE
Check Alertlog - Temp em local maior que o numero de linhas

### ISSUE THREAD

**Issue by bernardoVale** [bernardoVale/Monitoramento-Scripts#16]
Erro gerado:

Traceback (most recent call last):
  File "./lb2_oracle.py", line 133, in <module>
    main(sys.argv[1:])
  File "./lb2_oracle.py", line 105, in main
    database.run()
  File "./lb2_oracle.py", line 96, in run
    getattr(module_name, 'main')(**self.module)
  File "./check_alert.py", line 231, in main
    m.read_log()
  File "./check_alert.py", line 178, in read_log
    next(f)
StopIteration

Isso acontece ao excluir o alertlog por exemplo e o check_alertlog.tmp esta em uma linha mais avança que o tamanho do arquivo.

A lógica do check_alertlog.tmp deve ser revisada.

**Comment by bernardoVale** [comment]
Workarround: Excluir o check_alertlog.tmp

**Comment by bernardoVale** [comment]
Corrigido
